export const HOUSES_LIST_REQUEST = "HOUSES_LIST_REQUEST";
export const HOUSES_LIST_SUCCESS = "HOUSES_LIST_SUCCESS";
export const HOUSES_LIST_FAIL = "HOUSES_LIST_FAIL";

export const HOUSES_CREATE_REQUEST = "HOUSES_CREATE_REQUEST";
export const HOUSES_CREATE_SUCCESS = "HOUSES_CREATE_SUCCESS";
export const HOUSES_CREATE_FAIL = "HOUSES_CREATE_FAIL";

export const HOUSES_UPDATE_REQUEST = "HOUSES_UPDATE_REQUEST";
export const HOUSES_UPDATE_SUCCESS = "HOUSES_UPDATE_SUCCESS";
export const HOUSES_UPDATE_FAIL = "HOUSES_UPDATE_FAIL";

export const HOUSES_DELETE_REQUEST = "HOUSES_DELETE_REQUEST";
export const HOUSES_DELETE_SUCCESS = "HOUSES_DELETE_SUCCESS";
export const HOUSES_DELETE_FAIL = "HOUSES_DELETE_FAIL";
